name: mvcmovie-pipeline-feature-branches

on: 
  push:
    branches-ignore:
      - 'main'
      - 'release**'

jobs:
  build:
    name: Build and Test Application
    runs-on: [self-hosted, onprem]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
