name: mvcmovie-pipeline-release-branches

on: 
  push:
    branches:
      - 'release**'

jobs:
  build:
    name: Get Release Version
    runs-on: [self-hosted, onprem]

    steps:
    - name: Extract release version from branch name
      run: echo "$(echo ${GITHUB_REF#refs/heads/release/})"
      id: extract_release_version
